# ==================================================
# 镜像: viacooky/Caddy-Cloudflare
# 
# 描述: Caddy + Cloudflare 插件
# ==================================================
#
# 官网: https://caddyserver.com/
# 文档: https://caddyserver.com/docs/
# 仓库: https://github.com/caddyserver/caddy
# 插件: https://github.com/caddy-dns/cloudflare
#
# ==================================================
#
# 参考: 
# * https://github.com/caddyserver/caddy-docker/blob/aa3e73e0731fbca665be75edef9fbb60d3169278/2.10/alpine/Dockerfile
# * https://github.com/caddyserver/caddy-docker/blob/aa3e73e0731fbca665be75edef9fbb60d3169278/2.10/builder/Dockerfile


FROM caddy:__CADDY_VER__-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM caddy:__CADDY_VER__-alpine

LABEL   description="Caddy-Cloudflare" \
        version="__CADDY_VER__" \
        author="viacooky" \
        github="https://github.com/viacooky/Dockerfiles/Caddy-Cloudflare"

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

EXPOSE 80
EXPOSE 443
EXPOSE 443/udp
EXPOSE 2019

WORKDIR /svr

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]